# Target manifest: Sony HB-75P
TARGET_NAME = Sony HB-75P
OPENMSX_MACHINE_NAME = Sony_HB-75P
OPENMSX_MACHINE_XML = Sony_HB-75P.xml
ROM_IMAGE_NAME = msx-sony-hb75p_bootstrap.rom
IMAGE_LAYOUT = flash2x64
GEN_COMPACT_IMAGE = yes

# The HB-75P expansion port has a set of data bus buffers between it and
# the Z80 bus, not enabled at reset -- so unlike hb-55p/vg-8010, a ROM
# living on the expansion board's own flash (SST39SF010A) cannot supply
# slot 0's very first instruction fetch: the buffers block that data path
# in fresh-off-reset state. Cold boot now instead runs from a genuinely
# separate, unbuffered EEPROM physically placed in the machine's own
# original ROM socket (32 KB, e.g. 27C256/28C256). The two chips still use
# the exact same "identical bytes at the same offsets on both sides of the
# PSR switch" trick already described in the README (startup.s's
# _reset_vector remaps every page from slot0 to the destination slot in one
# `out`, and execution continues seamlessly because both chips hold the
# same code) -- only the physical chip supplying slot 0 has moved.
#
# GEN_MIRRORED_IMAGE stays at its default (yes): the expansion board's low
# bank (0x00000-0x0FFFF, "bootloader selected when ROM_OE is asserted") is
# permanently unreachable on this target since cold boot never touches this
# chip anymore, but the physical SST39SF010A is still a 128KB part --
# programmers like minipro expect a file matching the chip's full physical
# size (confirmed: minipro refused a 64KB file, "needs 131072B"), so
# ROM_IMAGE_NAME keeps mirroring startup.rom into both halves. The low
# half's actual content is irrelevant now (never read), only its size.

# EEPROM image for the original ROM socket (see above) -- byte-identical to
# startup.rom's first 32KB, generated by the existing GEN_COMPACT_IMAGE
# mechanism (previously only consumed by the ztick-unitcard openMSX
# simulation of this same staged-boot idea; now also a real flashable
# artifact for this target).
EEPROM_IMAGE_NAME = msx-sony-hb75p_eeprom.rom

# Link/load memory layout
ADDR_CODE  = 0x0040
ADDR_DATA  = 0x8000
ADDR_STACK = 0xF7FF

# Default application I/O port for io_write()/zbus
IO_DEFAULT_PORT = 0x38

# MSX -> zbridge FT245 RESET# trigger port (see zbridge/zbrc.py)
IO_RESET_PORT = 0x35

# Boot-time PPI/PSR configuration
PPI_CTRL_PORT = 0xAB
PPI_PSR_PORT = 0xA8
PPI_CTRL_VALUE = 0x82
BOOT_PSR_VALUE = 0x55
BOOT_MARKER_VALUE = 0x5A

# Boot-time autostart list: <task_name>:<weight>
BOOT_AUTOSTART = xsh:2
BOOT_AUTOSTART_STRICT = 1

# RCHK (RAM check) memory-switch probe configuration (target-defined, not user-defined).
# HB-75P internal RAM (slot 2) covers all 4 pages, but RCHK_EXEC_ADDR/
# RCHK_SAFE_SP below currently live in page 2's external RAM, so pages 0/1/3
# are candidates for extending this sweep, not page 2.
# page:slot:allowed_start:allowed_end:offset:length, one entry per internal-RAM page to sweep.
RCHK_TESTS = 3:2:0x0000:0x3FFF:0x0000:0x4000
RCHK_VALUE = 0xA5
RCHK_SAFE_MODE = safe
RCHK_SAFE_SP = 0xBFF0
RCHK_EXEC_ADDR = 0x8100
